---
- name: this will install apache2 on ubuntu
  hosts: test
  become: true
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present
  - name: start apache2
    service:
      name: apache2
      state: started

