---
- name: this playbook will install apache and start the apache servie.
  hosts: all
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
  - name : start httpd service
    service:
      name: httpd
      state: started
