---
- name: this play book displays how to use -  WHEN CONDITION.
  hosts: all
  become: true
  gather_facts: true
  tasks:
  - name: debug the script
    debug: 
      msg : "{{ ansible_facts.os_family }}"
  - name: install httpd on linux machine
    yum:
      name: httpd
      state: installed
    when: ansible_facts['os_family'] == "RedHat"
      #when: ansible_os_family == "RedHat"
  - name: start httpd service on linux machine
    service:
      name: httpd
      state: started
    when: ansible_facts['os_family'] == "RedHat"
        #when: ansible_os_family == "RedHat"
  - name: install apache2 on RHEL - Red Hat Enterprise Linux operating system
    apt:
      name: apacche2
      state: present
    when: ansible_facts['os_family'] == "Debian"
        #when: ansible_os_family == "Debian"
  - name: start apache2 on RHEL
    service:
      name: apache2
      state: started
    when: ansible_facts['os_family'] == "Debian"
        #when: ansible_os_family == "Debian"
